# Portfolioopdracht 1. Voorspel herseninfarct

In deze opdracht ontwikkelen en vergelijken we verschillende machine-learningmodellen om te voorspellen of een patiënt een verhoogd risico heeft op een herseninfarct. We analyseren en verwerken de data, evalueren modellen met geschikte metrics en verbeteren de prestaties met onder andere cross-validation, hyperparameter tuning en technieken voor imbalanced data. De modellen worden getest via Kaggle en uiteindelijk vergelijken we de resultaten om een onderbouwd modeladvies te geven.

### Groepsinformatie
#### Teamleden: 
Alisha 

Shalini

Baset

#### Teamnaam Kaggle: ABS

#### Gebruikersnamen Kaggle:
Alisha - alisharampersad

Shalini - shalinibekaroe

Baset - basetpaiman

## Opdracht 1. Exploratieve Data Analyse (EDA)

In dit hoofdstuk wordt de trainingsdataset onderzocht. Eerst bekijken we de structuur van de dataset en de betekenis van de verschillende kolommen. Daarna controleren we of de data geschikt is om te gebruiken voor Machine Learning met Scikit-learn.

In [4]:
#dataset inspecteren
import pandas as pd
df = pd.read_csv("train.csv")

df.head()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,gender_Other,ever_married_No,...,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,52709,30.0,0,0,63.60,33.3,False,True,False,True,...,False,True,False,False,True,False,False,False,True,0
1,72295,75.0,1,0,215.17,48.0,True,False,False,False,...,False,False,True,False,True,False,False,True,False,0
2,26451,15.0,0,0,135.22,19.0,False,True,False,True,...,False,True,False,False,True,False,False,True,False,0
3,65210,47.0,0,0,64.89,28.2,False,True,False,False,...,False,False,True,False,False,True,False,True,False,0
4,69299,49.0,0,0,222.34,28.8,False,True,False,False,...,False,False,True,False,True,False,True,False,False,0

### 1.3 Uitleg van de kolommen

| Kolom | Uitleg |
|---|---|
| `id` | Uniek identificatienummer van een patiënt. |
| `age` | Leeftijd van de patiënt. |
| `hypertension` | Geeft aan of de patiënt hypertensie (hoge bloeddruk) heeft. |
| `heart_disease` | Geeft aan of de patiënt een hartaandoening heeft. |
| `avg_glucose_level` | Gemiddeld glucosegehalte van de patiënt. |
| `bmi` | Body Mass Index (BMI) van de patiënt. |
| `gender_Female` | Dummyvariabele die aangeeft of de patiënt vrouw is. |
| `gender_Male` | Dummyvariabele die aangeeft of de patiënt man is. |
| `gender_Other` | Dummyvariabele voor patiënten met een andere geregistreerde gendercategorie. |
| `ever_married_No` | Dummyvariabele die aangeeft dat de patiënt nooit getrouwd is geweest. |
| `ever_married_Yes` | Dummyvariabele die aangeeft dat de patiënt getrouwd is of is geweest. |
| `work_type_Govt_job` | Dummyvariabele die aangeeft dat de patiënt bij de overheid werkt. |
| `work_type_Never_worked` | Dummyvariabele die aangeeft dat de patiënt nooit heeft gewerkt. |
| `work_type_Private` | Dummyvariabele die aangeeft dat de patiënt in de private sector werkt. |
| `work_type_Self-employed` | Dummyvariabele die aangeeft dat de patiënt zelfstandig ondernemer is. |
| `work_type_children` | Dummyvariabele die aangeeft dat de patiënt tot de categorie kinderen behoort. |
| `Residence_type_Rural` | Dummyvariabele die aangeeft dat de patiënt in een landelijk gebied woont. |
| `Residence_type_Urban` | Dummyvariabele die aangeeft dat de patiënt in een stedelijk gebied woont. |
| `smoking_status_formerly smoked` | Dummyvariabele die aangeeft dat de patiënt vroeger heeft gerookt. |
| `smoking_status_never smoked` | Dummyvariabele die aangeeft dat de patiënt nooit heeft gerookt. |
| `smoking_status_smokes` | Dummyvariabele die aangeeft dat de patiënt momenteel rookt. |
| `stroke` | Doelvariabele. Geeft aan of de patiënt een herseninfarct heeft gehad. |

In [14]:
#check of dataset voldoet aan eisen voor machine learning 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33550 entries, 0 to 33549
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              33550 non-null  int64
 1   age                             33550 non-null  float64
 2   hypertension                    33550 non-null  int64
 3   heart_disease                   33550 non-null  int64
 4   avg_glucose_level               33550 non-null  float64
 5   bmi                             33550 non-null  float64
 6   gender_Female                   33550 non-null  bool
 7   gender_Male                     33550 non-null  bool
 8   gender_Other                    33550 non-null  bool
 9   ever_married_No                 33550 non-null  bool
 10  ever_married_Yes                33550 non-null  bool
 11  work_type_Govt_job              33550 non-null  bool
 12  work_type_Never_worked          33550 non-null  bool
 13  work_type_Private               33550 non-null  bool
 14  work_type_Self-employed         33550 non-null  bool
 15  work_type_children              33550 non-null  bool
 16  Residence_type_Rural            33550 non-null  bool
 17  Residence_type_Urban            33550 non-null  bool
 18  smoking_status_formerly smoked  33550 non-null  bool
 19  smoking_status_never smoked     33550 non-null  bool
 20  smoking_status_smokes           33550 non-null  bool
 21  stroke                          33550 non-null  int64
dtypes: bool(15), float64(3), int64(4)
memory usage: 2.3 MB

### 1.4.1 ML vereisten
De data voldoet aan de eisen om machine learning toe te passen:

1.) De data is numeriek: De categorische variabelen zijn al grotendeels omgezet naar dummyvariabelen. Hierdoor zijn deze variabelen numeriek weergegeven.

2.) De data is in een Pandas Dataframe

3.) De data bevat geen missende waardes -> dit kunnen we zien aan 'non-null' bij alle kolommen

### 1.4.1 Datatypes en basisstatistieken

In [12]:
#datatypes weergeven
df.dtypes

id                                  int64
age                               float64
hypertension                        int64
heart_disease                       int64
avg_glucose_level                 float64
bmi                               float64
gender_Female                        bool
gender_Male                          bool
gender_Other                         bool
ever_married_No                      bool
ever_married_Yes                     bool
work_type_Govt_job                   bool
work_type_Never_worked               bool
work_type_Private                    bool
work_type_Self-employed              bool
work_type_children                   bool
Residence_type_Rural                 bool
Residence_type_Urban                 bool
smoking_status_formerly smoked       bool
smoking_status_never smoked          bool
smoking_status_smokes                bool
stroke                              int64
dtype: object

#### Toelichting datatypes
Een float is een getal met een decimaal

Een integer is een geheel getal

Een boolean is een waarde die True of False kan zijn

In [13]:
#basisstatistieken weergeven
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000,33550.000000
mean,36746.393353,41.815312,0.088137,0.043040,103.587081,28.601216,0.015410
std,20906.519131,22.477423,0.283498,0.202951,42.127396,7.782248,0.123178
min,1.000000,0.080000,0.000000,0.000000,55.010000,10.100000,0.000000
25%,18763.250000,24.000000,0.000000,0.000000,77.460000,23.300000,0.000000
50%,36862.000000,43.000000,0.000000,0.000000,91.320000,27.700000,0.000000
75%,54757.500000,59.000000,0.000000,0.000000,111.437500,32.800000,0.000000
max,72943.000000,82.000000,1.000000,1.000000,281.590000,97.600000,1.000000